# Generated by Django 6.0.4 on 2026-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_comentarios',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('hora_comentario', models.DateTimeField(auto_now_add=True)),
                ('detalle_comentario', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='comentarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_estado',
            fields=[
                ('id_estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('cerrado', 'Cerrado')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_prioridad',
            fields=[
                ('id_prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('id_prioridad', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, choices=[('resuelto', 'Resuelto'), ('error_aplicativo', 'Error de aplicativo'), ('error_usuario', 'Error de usuario'), ('falta_capacitacion', 'Falta de capacitación'), ('duplicado', 'Ticket duplicado'), ('no_corresponde', 'No corresponde a esta área')], max_length=255, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('tipo_soporte', models.CharField(max_length=255)),
                ('agencia_corresponsal', models.CharField(max_length=255)),
                ('administrativa', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
