# Generated by Django 6.0.4 on 2026-05-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaCorresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agencia / Corresponsal',
                'verbose_name_plural': 'Agencias y Corresponsales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AreaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Administrativa',
                'verbose_name_plural': 'Áreas Administrativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MotivoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Motivo de Cierre',
                'verbose_name_plural': 'Motivos de Cierre',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Soporte',
                'verbose_name_plural': 'Tipos de Soporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='ticket_estado',
            options={'verbose_name': 'Estado de Ticket', 'verbose_name_plural': 'Estados de Ticket'},
        ),
        migrations.AlterModelOptions(
            name='ticket_prioridad',
            options={'verbose_name': 'Prioridad de Ticket', 'verbose_name_plural': 'Prioridades de Ticket'},
        ),
        migrations.AddField(
            model_name='ticket_estado',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_prioridad',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket_estado',
            name='id_estado',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket_prioridad',
            name='id_prioridad',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id_estado',
            field=models.CharField(default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='id_prioridad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='agencia_corresponsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.agenciacorresponsal', verbose_name='Agencia / Corresponsal'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.areaadministrativa', verbose_name='Área Administrativa'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='motivo_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.motivocierre', verbose_name='Motivo de Cierre'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tipo_soporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.tiposoporte', verbose_name='Tipo de Soporte'),
        ),
    ]
