# Generated by Django 6.0.4 on 2026-05-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CAT_SOPORTE_TECNICO', 'Soporte Técnico'), ('CAT_SOPORTE_OPERATIVO', 'Soporte Operativo'), ('CAT_DESARROLLO', 'Área de Desarrollo')], max_length=255, null=True),
        ),
    ]
