# Generated by Django 6.0.4 on 2026-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador'), ('colaborador', 'Colaborador')], default='colaborador', max_length=255),
        ),
    ]
