# Generated by Django 6.0.4 on 2026-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Soporte Técnico', 'Soporte Técnico'), ('Soporte Operativo', 'Soporte Operativo'), ('Área de Desarrollo', 'Área de Desarrollo')], max_length=255, null=True),
        ),
    ]
